---
instance_details:
- instance_name: app1
  group: apps
  deployment: dev
  security_group_name: app_servers

- instance_name: app2
  group: apps
  deployment: dev
  security_group_name: app_servers

- instance_name: appdb1
  group: appdbs
  deployment: dev
  security_group_name: db_servers

- instance_name: frontend1
  group: frontends
  deployment: dev
  security_group_name: frontend_servers 
